---
- name: 'Package "python-software-properties" should be installed'
  apt:
    name: 'python-software-properties'
    state: present
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version is version_compare('16.04', '<=')

- name: 'Repositories should be updated (Ubuntu)'
  apt_repository:
    repo: "{{ graylog_java_ppa }}"
    state: present
    update_cache: true
  when: ansible_distribution == 'Ubuntu'

- name: 'Repositories should be updated (Debian)'
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - "{{ graylog_java_repo }}"
    - "{{ graylog_java_src_repo }}"
  when: ansible_distribution == 'Debian'

- name: 'APT Key should be accepted for the Java repo (Debian)'
  apt_key:
    keyserver: "{{ graylog_java_repo_keyserver }}"
    id: "{{ graylog_java_repo_key }}"
  when: ansible_distribution == 'Debian'


- name: Oracle license should be accepted
  debconf:
    name: "{{ graylog_java_oracle_installer_key }}"
    question: "shared/{{ graylog_java_oracle_license_key }}"
    value: 'true'
    vtype: 'select'

- name: Java 8 should be installed
  apt:
    name: 'oracle-java8-installer'
    state: present
    force: true

- name: Graylog repository package should be downloaded
  get_url:
    url: "{{ graylog_apt_deb_url }}"
    dest: '/tmp/graylog_repository.deb'

- name: 'Package "apt-transport-https" should be installed'
  apt:
    name: 'apt-transport-https'
    state: installed

- name: Graylog repository package should be installed
  apt:
    deb: '/tmp/graylog_repository.deb'
    state: installed
    dpkg_options: 'force-all'
  register: install_repo

- name: APT cache should be updated
  apt:
    update_cache: true
  when: install_repo.changed

- name: Graylog server package should be installed
  apt:
    name: 'graylog-server'
    state: present
  notify: restart graylog-server
